import { hasSupabaseConfig, supabase } from './lib/supabase'

export interface Match {
  date: string
  map: string
  teamOne: string
  teamTwo: string
  player1: string
  player2: string
  isTied: boolean
  isHomebrew: boolean
  isPlayer1Skip: boolean
  isPlayer2Skip: boolean
}

export type MapCategory = 'Open' | 'Close Quarters' | 'Hazardous Terrain'

export interface MapData {
  name: string
  category: MapCategory
  owners: string[]
}

const isMapCategory = (value: string): value is MapCategory =>
  value === 'Open' || value === 'Close Quarters' || value === 'Hazardous Terrain'

const normalizeMapCategory = (value?: string): MapCategory =>
  isMapCategory(value ?? '') ? (value as MapCategory) : 'Open'

const loadMaps = async (): Promise<MapData[]> => {
  if (!hasSupabaseConfig) {
    return FALLBACK_MAPS
  }

  const [{ data: mapRows, error: mapError }, { data: ownershipRows, error: ownershipError }] = await Promise.all([
    supabase.from('maps').select('id, name, category'),
    supabase.from('player_map_ownership').select('map_id, players(name)'),
  ])

  const mapRowsAny = Array.isArray(mapRows) ? (mapRows as any[]) : []
  const ownershipRowsAny = Array.isArray(ownershipRows) ? (ownershipRows as any[]) : []

  if (mapError || ownershipError || mapRowsAny.length === 0) {
    return FALLBACK_MAPS
  }

  const ownersByMapId = new Map<string, string[]>()

  for (const row of ownershipRowsAny) {
    const ownerInfo = Array.isArray(row.players) ? row.players[0] : row.players
    const ownerName = ownerInfo?.name
    if (!row.map_id || !ownerName) continue

    const owners = ownersByMapId.get(row.map_id) ?? []
    ownersByMapId.set(row.map_id, [...new Set([...owners, ownerName])])
  }

  return mapRowsAny.map((row: { id?: string; name?: string; category?: string }) => ({
    name: row.name ?? 'Unknown map',
    category: normalizeMapCategory(row.category),
    owners: row.id ? ownersByMapId.get(row.id) ?? [] : [],
  }))
}

const loadMatches = async (): Promise<Match[]> => {
  if (!hasSupabaseConfig) {
    return FALLBACK_MATCHES
  }

  const [
    { data: matchRows, error: matchError },
    { data: mapRows, error: mapError },
    { data: playerRows, error: playerError },
    { data: teamRows, error: teamError },
  ] = await Promise.all([
    supabase.from('matches').select('id, date, map_id, team_one_id, team_two_id, player_one_id, player_two_id, is_tied, is_homebrew, is_player_one_skip, is_player_two_skip'),
    supabase.from('maps').select('id, name'),
    supabase.from('players').select('id, name'),
    supabase.from('teams').select('id, name'),
  ])

  const matchRowsAny = Array.isArray(matchRows) ? (matchRows as any[]) : []
  const mapRowsAny = Array.isArray(mapRows) ? (mapRows as any[]) : []
  const playerRowsAny = Array.isArray(playerRows) ? (playerRows as any[]) : []
  const teamRowsAny = Array.isArray(teamRows) ? (teamRows as any[]) : []

  if (matchError || mapError || playerError || teamError || matchRowsAny.length === 0) {
    return FALLBACK_MATCHES
  }

  const mapIdByName = new Map((mapRowsAny as any[]).map((row) => [row.id, row.name]))
  const playerIdByName = new Map((playerRowsAny as any[]).map((row) => [row.id, row.name]))
  const teamIdByName = new Map((teamRowsAny as any[]).map((row) => [row.id, row.name]))

  const normalized = matchRowsAny
    .map((row: any) => {
      const mapName = row.map_id ? mapIdByName.get(row.map_id) : undefined
      const teamOne = row.team_one_id ? teamIdByName.get(row.team_one_id) : undefined
      const teamTwo = row.team_two_id ? teamIdByName.get(row.team_two_id) : undefined
      const player1 = row.player_one_id ? playerIdByName.get(row.player_one_id) : undefined
      const player2 = row.player_two_id ? playerIdByName.get(row.player_two_id) : undefined

      if (!mapName || !teamOne || !teamTwo || !player1 || !player2) {
        return null
      }

      return {
        date: row.date,
        map: mapName,
        teamOne,
        teamTwo,
        player1,
        player2,
        isTied: Boolean(row.is_tied),
        isHomebrew: Boolean(row.is_homebrew),
        isPlayer1Skip: Boolean(row.is_player_one_skip),
        isPlayer2Skip: Boolean(row.is_player_two_skip),
      }
    })
    .filter((match): match is Match => match !== null)

  return normalized.length > 0 ? normalized : FALLBACK_MATCHES
}

const FALLBACK_MAPS: MapData[] = [
  { name: 'Volkus', category: 'Open', owners: ['Chiep', 'Joao', 'Lucas', 'Gabriel'] },
  { name: 'Gallowdark', category: 'Close Quarters', owners: ['Joao', 'Rafa 1'] },
  { name: 'Tomb World', category: 'Close Quarters', owners: ['Joao', 'Rafa 1'] },
  { name: 'Octarius', category: 'Open', owners: ['Joao'] },
  { name: 'Nachmund', category: 'Open', owners: ['Joao'] },
  { name: 'Chalnath', category: 'Open', owners: ['Joao'] },
  { name: 'Bheta Decima', category: 'Hazardous Terrain', owners: ['Joao'] },
  { name: 'Ipiranga X', category: 'Open', owners: ['Joao'] },
  { name: 'Moroch', category: 'Open', owners: ['Joao'] },
  { name: 'Dust II', category: 'Open', owners: ['Rafa 1'] },
  { name: 'Sector Fatalis', category: 'Open', owners: ['Rafa 1'] },
  { name: 'WTC', category: 'Open', owners: ['Leon'] },
  { name: 'Bunda Secundus', category: 'Hazardous Terrain', owners: ['Davi'] },
]

const FALLBACK_MATCHES: Match[] = [
  { "date": "2026-08-28", "map": "WTC", "teamOne": "Spectres", "teamTwo": "Vespid Stingwings", "player1": "Leon", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-28", "map": "Gallowdark", "teamOne": "Hernkyn Yaegirs", "teamTwo": "Deathwatch", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-28", "map": "Sector Fatalis", "teamOne": "Kommandos", "teamTwo": "Plague Marines", "player1": "Davi", "player2": "Gabriel", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-21", "map": "Gallowdark", "teamOne": "Blooded", "teamTwo": "Corsair Voidscarred", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-21", "map": "Moroch", "teamOne": "Wolf Scouts", "teamTwo": "Wrecka Crew", "player1": "Rafa 1", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-21", "map": "Volkus", "teamOne": "Sanctifiers", "teamTwo": "Deathwatch", "player1": "Chiep", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-14", "map": "Moroch", "teamOne": "Spectres", "teamTwo": "Kommandos", "player1": "Leon", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-14", "map": "Gallowdark", "teamOne": "Salvagers", "teamTwo": "Raveners", "player1": "Rafa 1", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-14", "map": "WTC", "teamOne": "Deathwatch", "teamTwo": "Blooded", "player1": "Lucas", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-07", "map": "Gallowdark", "teamOne": "Blooded", "teamTwo": "Hearthkyn Salvagers", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-08-07", "map": "Dust II", "teamOne": "Tempestus Aquilons", "teamTwo": "Legionaries", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-31", "map": "Gallowdark", "teamOne": "Blooded", "teamTwo": "Death Korps", "player1": "Joao", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-31", "map": "Sector Fatalis", "teamOne": "Legionaries", "teamTwo": "Hearthkyn Salvagers", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-31", "map": "WTC", "teamOne": "Tempestus Aquilons", "teamTwo": "Goremongers", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-24", "map": "Chalnath", "teamOne": "Legionaries", "teamTwo": "Imperial Navy Breachers", "player1": "Davi", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-24", "map": "Sector Fatalis", "teamOne": "Fellgor Ravagers", "teamTwo": "Tempestus Aquilons", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-17", "map": "Gallowdark", "teamOne": "Imperial Navy Breachers", "teamTwo": "Goremongers", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-17", "map": "Sector Fatalis", "teamOne": "Kasrkin", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Gabriel", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-10", "map": "Dust II", "teamOne": "Exaction Squad", "teamTwo": "Wrecka Crew", "player1": "Leon", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-10", "map": "WTC", "teamOne": "Imperial Navy Breachers", "teamTwo": "Kasrkin", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-10", "map": "Gallowdark", "teamOne": "Tempestus Aquilons", "teamTwo": "Exaction Squad", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-10", "map": "Volkus", "teamOne": "XV26 Stealth Battlesuits", "teamTwo": "Angels of Death", "player1": "Chiep", "player2": "Gabriel", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-03", "map": "Dust II", "teamOne": "Tempestus Aquilons", "teamTwo": "Imperial Navy Breachers", "player1": "Lucas", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-07-03", "map": "Moroch", "teamOne": "Exaction Squad", "teamTwo": "Kasrkin", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-26", "map": "Gallowdark", "teamOne": "Hunter Clade", "teamTwo": "Kasrkin", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-26", "map": "WTC", "teamOne": "Goremongers", "teamTwo": "Exaction Squad", "player1": "Leon", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-19", "map": "Bheta Decima", "teamOne": "Hunter Clade", "teamTwo": "Exaction Squad", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-19", "map": "Moroch", "teamOne": "Wrecka Crew", "teamTwo": "Celestial Insidiants", "player1": "Rafa 2", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-12", "map": "WTC", "teamOne": "Brood Brothers", "teamTwo": "Exaction Squad", "player1": "Rafa 1", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-12", "map": "Gallowdark", "teamOne": "Celestial Insidiants", "teamTwo": "Goremongers", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-05", "map": "Volkus", "teamOne": "Imperial Navy Breachers", "teamTwo": "Kommandos", "player1": "Joao", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-06-05", "map": "Tomb World", "teamOne": "Ratlings", "teamTwo": "Wrecka Crew", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-29", "map": "WTC", "teamOne": "Goremongers", "teamTwo": "Wrecka Crew", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-29", "map": "Volkus", "teamOne": "XV26 Stealth Battlesuits", "teamTwo": "Wolf Scouts", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-29", "map": "Volkus", "teamOne": "Blades of Khaine", "teamTwo": "Hearthkyn Salvagers", "player1": "Chiep", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-22", "map": "Dust II", "teamOne": "Kommandos", "teamTwo": "Ratlings", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-22", "map": "Volkus", "teamOne": "Death Korps", "teamTwo": "Wrecka Crew", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-15", "map": "WTC", "teamOne": "Celestial Insidiants", "teamTwo": "Hearthkyn Salvagers", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-15", "map": "Volkus", "teamOne": "Exaction Squad", "teamTwo": "Ratlings", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-08", "map": "Nachmund", "teamOne": "Elucidian Starstriders", "teamTwo": "Plague Marines", "player1": "Joao", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-08", "map": "Tomb World", "teamOne": "Wolf Scouts", "teamTwo": "Spectres", "player1": "Rafa 1", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-01", "map": "Ipiranga X", "teamOne": "Hearthkyn Salvagers", "teamTwo": "Fellgor Ravagers", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-01", "map": "WTC", "teamOne": "Celestial Insidiants", "teamTwo": "Exaction Squad", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-05-01", "map": "Tomb World", "teamOne": "Battleclade", "teamTwo": "Farstalker Kinband", "player1": "Joao", "player2": "Davi", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-24", "map": "WTC", "teamOne": "Exaction Squad", "teamTwo": "Hearthkyn Salvagers", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-24", "map": "Tomb World", "teamOne": "Celestial Insidiants", "teamTwo": "Hierotek Circle", "player1": "Lucas", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-17", "map": "Volkus", "teamOne": "Chaos Cult", "teamTwo": "Goremongers", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-17", "map": "Moroch", "teamOne": "Celestial Insidiants", "teamTwo": "Wolf Scouts", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-10", "map": "Gallowdark", "teamOne": "Celestial Insidiants", "teamTwo": "Raveners", "player1": "Lucas", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-10", "map": "Chalnath", "teamOne": "Hierotek Circle", "teamTwo": "Wolf Scouts", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-03", "map": "Gallowdark", "teamOne": "Hierotek Circle", "teamTwo": "Exaction Squad", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-04-03", "map": "Dust II", "teamOne": "Wolf Scouts", "teamTwo": "XV26 Stealth Battlesuits", "player1": "Rafa 1", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-03-27", "map": "Tomb World", "teamOne": "Hearthkyn Salvagers", "teamTwo": "Death Korps", "player1": "Davi", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-03-27", "map": "Volkus", "teamOne": "Deathwatch", "teamTwo": "Wolf Scouts", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-03-13", "map": "Gallowdark", "teamOne": "Legionaries", "teamTwo": "Blooded", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-03-13", "map": "Volkus", "teamOne": "Deathwatch", "teamTwo": "Plague Marines", "player1": "Lucas", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-03-06", "map": "Dust II", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Gabriel", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-03-06", "map": "Volkus", "teamOne": "Elucidian Starstriders", "teamTwo": "Exaction Squad", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-27", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Darc", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-27", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Darc", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-27", "map": "Tomb World", "teamOne": "Deathwatch", "teamTwo": "Deathwatch", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-27", "map": "Volkus", "teamOne": "Fellgor Ravagers", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Matheus", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-20", "map": "Ipiranga X", "teamOne": "Greenskins", "teamTwo": "Angels of Death", "player1": "Davi", "player2": "Matheus", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-20", "map": "Gallowdark", "teamOne": "Elucidian Starstriders", "teamTwo": "Deathwatch", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-13", "map": "Dust II", "teamOne": "Angels of Death", "teamTwo": "Vespid Stingwings", "player1": "Joao", "player2": "Vitor", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-13", "map": "Octarius", "teamOne": "Exaction Squad", "teamTwo": "Deathwatch", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-13", "map": "Gallowdark", "teamOne": "Kasrkin", "teamTwo": "Deathwatch", "player1": "Rafa 1", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-06", "map": "Dust II", "teamOne": "XV26 Stealth Battlesuits", "teamTwo": "Kommandos", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-02-06", "map": "Ipiranga X", "teamOne": "Kasrkin", "teamTwo": "Exaction Squad", "player1": "Rafa 1", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-30", "map": "Volkus", "teamOne": "XV26 Stealth Battlesuits", "teamTwo": "Exaction Squad", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-30", "map": "Moroch", "teamOne": "Deathwatch", "teamTwo": "Deathwatch", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-23", "map": "Bheta Decima", "teamOne": "XV26 Stealth Battlesuits", "teamTwo": "Tempestus Aquilons", "player1": "Joao", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-23", "map": "Chalnath", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Matheus", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-23", "map": "Chalnath", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Matheus", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-16", "map": "Bheta Decima", "teamOne": "Wrecka Crew", "teamTwo": "Goremongers", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-16", "map": "Octarius", "teamOne": "Farstalker Kinband", "teamTwo": "Brood Brothers", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-09", "map": "Ipiranga X", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Matheus", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-09", "map": "Moroch", "teamOne": "Farstalker Kinband", "teamTwo": "Angels of Death", "player1": "Davi", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-09", "map": "Dust II", "teamOne": "Elucidian Starstriders", "teamTwo": "Brood Brothers", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-02", "map": "Tomb World", "teamOne": "Goremongers", "teamTwo": "Wrecka Crew", "player1": "Davi", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2026-01-02", "map": "Nachmund", "teamOne": "Death Korps", "teamTwo": "Plague Marines", "player1": "Joao", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-26", "map": "Tomb World", "teamOne": "Blooded", "teamTwo": "Wrecka Crew", "player1": "Rafa 1", "player2": "Lucas", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-26", "map": "Volkus", "teamOne": "Kommandos", "teamTwo": "Chaos Cult", "player1": "Davi", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-19", "map": "Tomb World", "teamOne": "Angels of Death", "teamTwo": "Kommandos", "player1": "Matheus", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-19", "map": "Volkus", "teamOne": "Battleclade", "teamTwo": "Wrecka Crew", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-19", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Blooded", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-12", "map": "Tomb World", "teamOne": "Wrecka Crew", "teamTwo": "Hearthkyn Salvagers", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-05", "map": "Dust II", "teamOne": "Hernkyn Yaegirs", "teamTwo": "Wrecka Crew", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-05", "map": "Volkus", "teamOne": "Angels of Death", "teamTwo": "Goremongers", "player1": "Leon", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-12-05", "map": "Volkus", "teamOne": "Battleclade", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-28", "map": "Ipiranga X", "teamOne": "Goremongers", "teamTwo": "Hernkyn Yaegirs", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-28", "map": "Dust II", "teamOne": "Battleclade", "teamTwo": "Wrecka Crew", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-21", "map": "Tomb World", "teamOne": "Chaos Cult", "teamTwo": "Hernkyn Yaegirs", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-14", "map": "Volkus", "teamOne": "Chaos Cult", "teamTwo": "Tempestus Aquilons", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-14", "map": "Volkus", "teamOne": "Tempestus Aquilons", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Leon", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-07", "map": "Dust II", "teamOne": "Battleclade", "teamTwo": "Goremongers", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-11-07", "map": "Volkus", "teamOne": "Wyrmblade", "teamTwo": "Blooded", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-31", "map": "Tomb World", "teamOne": "Goremongers", "teamTwo": "Brood Brothers", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-31", "map": "Volkus", "teamOne": "Ecclesiarchy", "teamTwo": "Ogryns", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-31", "map": "Volkus", "teamOne": "Ogryns", "teamTwo": "Ecclesiarchy", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-24", "map": "Tomb World", "teamOne": "Hand of the Archon", "teamTwo": "Novitiates", "player1": "Joao", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-24", "map": "Moroch", "teamOne": "Ratlings", "teamTwo": "Goremongers", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-17", "map": "Tomb World", "teamOne": "Angels of Death", "teamTwo": "Ratlings", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-17", "map": "Volkus", "teamOne": "Wyrmblade", "teamTwo": "Goremongers", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-10", "map": "Dust II", "teamOne": "Plague Marines", "teamTwo": "Pathfinders", "player1": "Rubens", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-10", "map": "Tomb World", "teamOne": "Battleclade", "teamTwo": "Goremongers", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-10", "map": "Gallowdark", "teamOne": "Raveners", "teamTwo": "Ratlings", "player1": "Chiep", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-10", "map": "Volkus", "teamOne": "Ecclesiarchy", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-03", "map": "Dust II", "teamOne": "Battleclade", "teamTwo": "Blooded", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-10-03", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Vespid Stingwings", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-26", "map": "Dust II", "teamOne": "Hearthkyn Salvagers", "teamTwo": "Kasrkin", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-26", "map": "Dust II", "teamOne": "Ecclesiarchy", "teamTwo": "Hernkyn Yaegirs", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-26", "map": "Nachmund", "teamOne": "Battleclade", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-19", "map": "Tomb World", "teamOne": "Corsair Voidscarred", "teamTwo": "Ecclesiarchy", "player1": "Davi", "player2": "Lucas", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-19", "map": "Tomb World", "teamOne": "Battleclade", "teamTwo": "Kommandos", "player1": "Joao", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-12", "map": "Volkus", "teamOne": "Corsair Voidscarred", "teamTwo": "Ecclesiarchy", "player1": "Davi", "player2": "Lucas", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-12", "map": "Volkus", "teamOne": "Corsair Voidscarred", "teamTwo": "Hernkyn Yaegirs", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-12", "map": "Moroch", "teamOne": "Battleclade", "teamTwo": "Ecclesiarchy", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-05", "map": "Gallowdark", "teamOne": "Wyrmblade", "teamTwo": "Hierotek Circle", "player1": "Lucas", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-05", "map": "Octarius", "teamOne": "Battleclade", "teamTwo": "Warpcoven", "player1": "Joao", "player2": "Rubens", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-09-05", "map": "Nachmund", "teamOne": "Hernkyn Yaegirs", "teamTwo": "Nemesis Claw", "player1": "Rafa 1", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-29", "map": "Gallowdark", "teamOne": "Ecclesiarchy", "teamTwo": "Corsair Voidscarred", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-29", "map": "Volkus", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Rubens", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-29", "map": "Volkus", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Rubens", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-22", "map": "Chalnath", "teamOne": "Goremongers", "teamTwo": "Exaction Squad", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-22", "map": "Bheta Decima", "teamOne": "Hand of the Archon", "teamTwo": "Kasrkin", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-15", "map": "Moroch", "teamOne": "Plague Marines", "teamTwo": "Goremongers", "player1": "Chiep", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-15", "map": "Octarius", "teamOne": "Blades of Khaine", "teamTwo": "Brood Brothers", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-15", "map": "Gallowdark", "teamOne": "Kommandos", "teamTwo": "Novitiates", "player1": "Davi", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-08", "map": "Bheta Decima", "teamOne": "Vespid Stingwings", "teamTwo": "Kommandos", "player1": "Chiep", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-08", "map": "Bheta Decima", "teamOne": "Plague Marines", "teamTwo": "Pathfinders", "player1": "Chiep", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-08", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Rubens", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-08", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Rubens", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-08", "map": "Gallowdark", "teamOne": "Blades of Khaine", "teamTwo": "Tempestus Aquilons", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-01", "map": "Volkus", "teamOne": "Brood Brothers", "teamTwo": "Pathfinders", "player1": "Rafa 1", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-01", "map": "Ipiranga X", "teamOne": "Sanctifiers", "teamTwo": "Ogryns", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-08-01", "map": "Bunda Secundus", "teamOne": "Death Korps", "teamTwo": "Novitiates", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-25", "map": "Volkus", "teamOne": "Ogryns", "teamTwo": "Brood Brothers", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-25", "map": "Bheta Decima", "teamOne": "Death Korps", "teamTwo": "Tempestus Aquilons", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-18", "map": "Gallowdark", "teamOne": "Novitiates", "teamTwo": "Pathfinders", "player1": "Davi", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-18", "map": "Chalnath", "teamOne": "Tempestus Aquilons", "teamTwo": "Hearthkyn Salvagers", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-11", "map": "Gallowdark", "teamOne": "Goremongers", "teamTwo": "Hearthkyn Salvagers", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-11", "map": "Moroch", "teamOne": "Blades of Khaine", "teamTwo": "Tempestus Aquilons", "player1": "Joao", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-04", "map": "Gallowdark", "teamOne": "Ogryns", "teamTwo": "Hearthkyn Salvagers", "player1": "Leon", "player2": "Davi", "isTied": false, "isHomebrew": true, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-04", "map": "Volkus", "teamOne": "Goremongers", "teamTwo": "Death Korps", "player1": "Lucas", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-07-04", "map": "Ipiranga X", "teamOne": "Blades of Khaine", "teamTwo": "Hearthkyn Salvagers", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-27", "map": "Gallowdark", "teamOne": "Legionaries", "teamTwo": "Death Korps", "player1": "Leon", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-27", "map": "Gallowdark", "teamOne": "Legionaries", "teamTwo": "Death Korps", "player1": "Leon", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-27", "map": "Octarius", "teamOne": "Goremongers", "teamTwo": "Fellgor Ravagers", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-27", "map": "Volkus", "teamOne": "Hunter Clade", "teamTwo": "Hearthkyn Salvagers", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-20", "map": "Moroch", "teamOne": "Fellgor Ravagers", "teamTwo": "Hearthkyn Salvagers", "player1": "Rafa 1", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-20", "map": "Gallowdark", "teamOne": "Hunter Clade", "teamTwo": "Kommandos", "player1": "Joao", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-13", "map": "Moroch", "teamOne": "Ratlings", "teamTwo": "Hearthkyn Salvagers", "player1": "Rafa 1", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-13", "map": "Ipiranga X", "teamOne": "Legionaries", "teamTwo": "Goremongers", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-06", "map": "Nachmund", "teamOne": "Angels of Death", "teamTwo": "Goremongers", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-06", "map": "Nachmund", "teamOne": "Angels of Death", "teamTwo": "Goremongers", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-06", "map": "Gallowdark", "teamOne": "Kommandos", "teamTwo": "Hearthkyn Salvagers", "player1": "Rafa 2", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-06-06", "map": "Bunda Secundus", "teamOne": "Chaos Cult", "teamTwo": "Blooded", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-30", "map": "Gallowdark", "teamOne": "Sanctifiers", "teamTwo": "Fellgor Ravagers", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-23", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Eddie", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-23", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Eddie", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-23", "map": "Gallowdark", "teamOne": "Sanctifiers", "teamTwo": "Kasrkin", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-23", "map": "Chalnath", "teamOne": "Death Korps", "teamTwo": "Hearthkyn Salvagers", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-23", "map": "Volkus", "teamOne": "Vespid Stingwings", "teamTwo": "Tempestus Aquilons", "player1": "Chiep", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-16", "map": "Gallowdark", "teamOne": "Legionaries", "teamTwo": "Death Korps", "player1": "Leon", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-16", "map": "Octarius", "teamOne": "Sanctifiers", "teamTwo": "Sanctifiers", "player1": "Chiep", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-16", "map": "Bheta Decima", "teamOne": "Hearthkyn Salvagers", "teamTwo": "Blooded", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-09", "map": "Gallowdark", "teamOne": "Tempestus Aquilons", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-09", "map": "Octarius", "teamOne": "Hand of the Archon", "teamTwo": "Plague Marines", "player1": "Joao", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-09", "map": "Volkus", "teamOne": "Death Korps", "teamTwo": "Exaction Squad", "player1": "Rafa 2", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-02", "map": "Gallowdark", "teamOne": "Death Korps", "teamTwo": "Elucidian Starstriders", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-05-02", "map": "Moroch", "teamOne": "Hand of the Archon", "teamTwo": "Kommandos", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-25", "map": "Gallowdark", "teamOne": "Nemesis Claw", "teamTwo": "Phobos Strike Team", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-25", "map": "Chalnath", "teamOne": "Legionaries", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-18", "map": "Volkus", "teamOne": "Sanctifiers", "teamTwo": "Corsair Voidscarred", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-18", "map": "Gallowdark", "teamOne": "Void-dancer Troupe", "teamTwo": "Kommandos", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-18", "map": "Ipiranga X", "teamOne": "Death Korps", "teamTwo": "Ratlings", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-11", "map": "Moroch", "teamOne": "Hand of the Archon", "teamTwo": "Farstalker Kinband", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-11", "map": "Gallowdark", "teamOne": "Blooded", "teamTwo": "Kommandos", "player1": "Rafa 1", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-11", "map": "Bheta Decima", "teamOne": "Nemesis Claw", "teamTwo": "Plague Marines", "player1": "Leon", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-04", "map": "Bunda Secundus", "teamOne": "Plague Marines", "teamTwo": "Novitiates", "player1": "Chiep", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-04-04", "map": "Gallowdark", "teamOne": "Wyrmblade", "teamTwo": "Exaction Squad", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-28", "map": "Octarius", "teamOne": "Wyrmblade", "teamTwo": "Chaos Cult", "player1": "Lucas", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-28", "map": "Chalnath", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Rafa 1", "player2": "Vitor Monte Mor", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-28", "map": "Gallowdark", "teamOne": "Novitiates", "teamTwo": "Hierotek Circle", "player1": "Rafa 2", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-21", "map": "Bheta Decima", "teamOne": "Angels of Death", "teamTwo": "Vespid Stingwings", "player1": "Davi", "player2": "Vitor Monte Mor", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-21", "map": "Moroch", "teamOne": "Plague Marines", "teamTwo": "Fellgor Ravagers", "player1": "Chiep", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-21", "map": "Bunda Secundus", "teamOne": "Angels of Death", "teamTwo": "Wyrmblade", "player1": "Davi", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-21", "map": "Gallowdark", "teamOne": "Chaos Cult", "teamTwo": "Novitiates", "player1": "Joao", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-14", "map": "Gallowdark", "teamOne": "Plague Marines", "teamTwo": "Wyrmblade", "player1": "Chiep", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-14", "map": "Octarius", "teamOne": "Kommandos", "teamTwo": "Kommandos", "player1": "Davi", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-14", "map": "Nachmund", "teamOne": "Angels of Death", "teamTwo": "Kasrkin", "player1": "Leon", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-14", "map": "Volkus", "teamOne": "Chaos Cult", "teamTwo": "Vespid Stingwings", "player1": "Joao", "player2": "Vitor Monte Mor", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-07", "map": "Volkus", "teamOne": "Farstalker Kinband", "teamTwo": "Hearthkyn Salvagers", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-07", "map": "Moroch", "teamOne": "Death Korps", "teamTwo": "Hierotek Circle", "player1": "Rafa 2", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-03-07", "map": "Bheta Decima", "teamOne": "Hand of the Archon", "teamTwo": "Tempestus Aquilons", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-28", "map": "Bunda Secundus", "teamOne": "Farstalker Kinband", "teamTwo": "Kommandos", "player1": "Davi", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-28", "map": "Gallowdark", "teamOne": "Vespid Stingwings", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-21", "map": "Ipiranga X", "teamOne": "Tempestus Aquilons", "teamTwo": "Kommandos", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-21", "map": "Volkus", "teamOne": "Blades of Khaine", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-14", "map": "Gallowdark", "teamOne": "Angels of Death", "teamTwo": "Kommandos", "player1": "Rafa 1", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-14", "map": "Gallowdark", "teamOne": "Nemesis Claw", "teamTwo": "Blades of Khaine", "player1": "Leon", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-14", "map": "Gallowdark", "teamOne": "Tempestus Aquilons", "teamTwo": "Farstalker Kinband", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-14", "map": "Volkus", "teamOne": "Vespid Stingwings", "teamTwo": "Blades of Khaine", "player1": "Lucas", "player2": "Chiep", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-07", "map": "Ipiranga X", "teamOne": "Vespid Stingwings", "teamTwo": "Angels of Death", "player1": "Lucas", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-07", "map": "Moroch", "teamOne": "Death Korps", "teamTwo": "Blades of Khaine", "player1": "Rafa 2", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-02-07", "map": "Gallowdark", "teamOne": "Ratlings", "teamTwo": "Farstalker Kinband", "player1": "Rafa 1", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-31", "map": "Chalnath", "teamOne": "Nemesis Claw", "teamTwo": "Kommandos", "player1": "Leon", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-31", "map": "Volkus", "teamOne": "Blades of Khaine", "teamTwo": "Farstalker Kinband", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-31", "map": "Gallowdark", "teamOne": "Ratlings", "teamTwo": "Tempestus Aquilons", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-24", "map": "Bheta Decima", "teamOne": "Kommandos", "teamTwo": "Farstalker Kinband", "player1": "Rafa 2", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-24", "map": "Moroch", "teamOne": "Blades of Khaine", "teamTwo": "Hunter Clade", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-17", "map": "Ipiranga X", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Eddie", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-17", "map": "Volkus", "teamOne": "Phobos Strike Team", "teamTwo": "Hunter Clade", "player1": "Davi", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-17", "map": "Gallowdark", "teamOne": "Ratlings", "teamTwo": "Nemesis Claw", "player1": "Rafa 1", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-10", "map": "Octarius", "teamOne": "Corsair Voidscarred", "teamTwo": "Nemesis Claw", "player1": "Davi", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-10", "map": "Volkus", "teamOne": "Death Korps", "teamTwo": "Wyrmblade", "player1": "Rafa 2", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-10", "map": "Chalnath", "teamOne": "Blades of Khaine", "teamTwo": "Ratlings", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2025-01-03", "map": "Gallowdark", "teamOne": "Pathfinders", "teamTwo": "Void-dancer Troupe", "player1": "Joao", "player2": "Lucas", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-27", "map": "Volkus", "teamOne": "Exaction Squad", "teamTwo": "Death Korps", "player1": "Rafa 1", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-20", "map": "Ipiranga X", "teamOne": "Kommandos", "teamTwo": "Pathfinders", "player1": "Rafa 2", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-20", "map": "Moroch", "teamOne": "Vespid Stingwings", "teamTwo": "Kasrkin", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-13", "map": "Nachmund", "teamOne": "Pathfinders", "teamTwo": "Kasrkin", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-13", "map": "Gallowdark", "teamOne": "Corsair Voidscarred", "teamTwo": "Kommandos", "player1": "Davi", "player2": "Rafa 2", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-13", "map": "Bunda Secundus", "teamOne": "Nemesis Claw", "teamTwo": "Vespid Stingwings", "player1": "Leon", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-06", "map": "Octarius", "teamOne": "Angels of Death", "teamTwo": "Nemesis Claw", "player1": "Rafa 1", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-06", "map": "Chalnath", "teamOne": "Corsair Voidscarred", "teamTwo": "Vespid Stingwings", "player1": "Davi", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-12-06", "map": "Octarius", "teamOne": "Nemesis Claw", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-29", "map": "Octarius", "teamOne": "Hand of the Archon", "teamTwo": "Phobos Strike Team", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-29", "map": "Moroch", "teamOne": "Corsair Voidscarred", "teamTwo": "Exaction Squad", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-22", "map": "Gallowdark", "teamOne": "Hand of the Archon", "teamTwo": "Corsair Voidscarred", "player1": "Joao", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-22", "map": "Volkus", "teamOne": "Void-dancer Troupe", "teamTwo": "Exaction Squad", "player1": "Lucas", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-15", "map": "Ipiranga X", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Giordano", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-15", "map": "Ipiranga X", "teamOne": "Angels of Death", "teamTwo": "Angels of Death", "player1": "Joao", "player2": "Giordano", "isTied": true, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-15", "map": "Gallowdark", "teamOne": "Blooded", "teamTwo": "Nemesis Claw", "player1": "Rafa 1", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-15", "map": "Bunda Secundus", "teamOne": "Void-dancer Troupe", "teamTwo": "Kommandos", "player1": "Lucas", "player2": "Davi", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-08", "map": "Gallowdark", "teamOne": "Novitiates", "teamTwo": "Blooded", "player1": "Davi", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-08", "map": "Bheta Decima", "teamOne": "Hand of the Archon", "teamTwo": "Hunter Clade", "player1": "Joao", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-01", "map": "Gallowdark", "teamOne": "Kommandos", "teamTwo": "Nemesis Claw", "player1": "Davi", "player2": "Leon", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-11-01", "map": "Bheta Decima", "teamOne": "Hand of the Archon", "teamTwo": "Hearthkyn Salvagers", "player1": "Joao", "player2": "Rafa 1", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-10-25", "map": "Volkus", "teamOne": "Kommandos", "teamTwo": "Death Korps", "player1": "Davi", "player2": "Joao", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false },
  { "date": "2024-10-25", "map": "Bunda Secundus", "teamOne": "Kasrkin", "teamTwo": "Wyrmblade", "player1": "Rafa 1", "player2": "Lucas", "isTied": false, "isHomebrew": false, "isPlayer1Skip": false, "isPlayer2Skip": false }
]

export const TEAMS = [
  [
  {
    "killTeam": "Strike Force Variel",
    "genericFaction": "Imperium",
    "fortyKFaction": "Space Marines",
    "season": 0,
    "boxNumber": "Warhammer Heroes 6",
    "boxName": "Warhammer Heroes 6",
    "category": "Elite",
    "operatives": 6,
    "wounds": 82,
    "apl": 18,
    "releaseDate": "2025-08-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 80,
    "maxWounds": 82,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Hunter Clade",
    "genericFaction": "Imperium",
    "fortyKFaction": "Adeptus Mechanicus",
    "season": 0,
    "boxNumber": "White Dwarf",
    "boxName": "Annual 2022",
    "category": "Standard",
    "operatives": 10,
    "wounds": 86,
    "apl": 20,
    "releaseDate": "2022-08-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 71,
    "maxWounds": 86,
    "minApl": 20,
    "maxApl": 20,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Void-dancer Troupe",
    "genericFaction": "Xenos",
    "fortyKFaction": "Aeldari",
    "season": 0,
    "boxNumber": "White Dwarf",
    "boxName": "Annual 2022",
    "category": "Semi-Elite",
    "operatives": 8,
    "wounds": 67,
    "apl": 24,
    "releaseDate": "2022-08-01",
    "minOperatives": 8,
    "maxOperatives": 8,
    "minWounds": 65,
    "maxWounds": 67,
    "minApl": 24,
    "maxApl": 24,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 8,
    "trooperApl": 3
  },
  {
    "killTeam": "Gellerpox Infected",
    "genericFaction": "Chaos",
    "fortyKFaction": "Death Guard",
    "season": 0,
    "boxNumber": "White Dwarf",
    "boxName": "Annual 2022",
    "category": "Horde",
    "operatives": 15,
    "wounds": 122,
    "apl": 30,
    "releaseDate": "2019-06-01",
    "minOperatives": 11,
    "maxOperatives": 15,
    "minWounds": 114,
    "maxWounds": 122,
    "minApl": 22,
    "maxApl": 30,
    "minActivations": 8,
    "maxActivations": 10,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Wyrmblade",
    "genericFaction": "Xenos",
    "fortyKFaction": "Genestealer Cults",
    "season": 0,
    "boxNumber": "White Dwarf",
    "boxName": "Annual 2022",
    "category": "Horde",
    "operatives": 12,
    "wounds": 89,
    "apl": 26,
    "releaseDate": "2022-08-01",
    "minOperatives": 12,
    "maxOperatives": 14,
    "minWounds": 89,
    "maxWounds": 99,
    "minApl": 26,
    "maxApl": 28,
    "minActivations": 8,
    "maxActivations": 10,
    "killOp": 12,
    "trooperApl": 2
  },
  {
    "killTeam": "Elucidian Starstriders",
    "genericFaction": "Imperium",
    "fortyKFaction": "Imperial Agents",
    "season": 0,
    "boxNumber": "White Dwarf",
    "boxName": "Annual 2022",
    "category": "Standard",
    "operatives": 10,
    "wounds": 75,
    "apl": 22,
    "releaseDate": "2019-06-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 75,
    "maxWounds": 75,
    "minApl": 22,
    "maxApl": 22,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Warpcoven",
    "genericFaction": "Chaos",
    "fortyKFaction": "Thousand Sons",
    "season": 0,
    "boxNumber": "White Dwarf",
    "boxName": "Annual 2022",
    "category": "Semi-Elite",
    "operatives": 7,
    "wounds": 82,
    "apl": 17,
    "releaseDate": "2022-08-01",
    "minOperatives": 5,
    "maxOperatives": 9,
    "minWounds": 73,
    "maxWounds": 88,
    "minApl": 15,
    "maxApl": 19,
    "minActivations": 5,
    "maxActivations": 9,
    "killOp": 7,
    "trooperApl": 3
  },
  {
    "killTeam": "Death Korps",
    "genericFaction": "Imperium",
    "fortyKFaction": "Astra Militarum",
    "season": 1,
    "boxNumber": 1,
    "boxName": "Octarius",
    "category": "Horde",
    "operatives": 13,
    "wounds": 92,
    "apl": 26,
    "releaseDate": "2021-08-01",
    "minOperatives": 10,
    "maxOperatives": 14,
    "minWounds": 71,
    "maxWounds": 99,
    "minApl": 20,
    "maxApl": 28,
    "minActivations": 6,
    "maxActivations": 12,
    "killOp": 13,
    "trooperApl": 2
  },
  {
    "killTeam": "Kommandos",
    "genericFaction": "Xenos",
    "fortyKFaction": "Orks",
    "season": 1,
    "boxNumber": 1,
    "boxName": "Octarius",
    "category": "Horde",
    "operatives": 11,
    "wounds": 104,
    "apl": 23,
    "releaseDate": "2021-08-01",
    "minOperatives": 10,
    "maxOperatives": 11,
    "minWounds": 104,
    "maxWounds": 104,
    "minApl": 21,
    "maxApl": 23,
    "minActivations": 10,
    "maxActivations": 11,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Novitiates",
    "genericFaction": "Imperium",
    "fortyKFaction": "Adepta Sororitas",
    "season": 1,
    "boxNumber": 2,
    "boxName": "Chalnath",
    "category": "Standard",
    "operatives": 10,
    "wounds": 72,
    "apl": 21,
    "releaseDate": "2021-11-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 72,
    "maxWounds": 72,
    "minApl": 21,
    "maxApl": 21,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Pathfinders",
    "genericFaction": "Xenos",
    "fortyKFaction": "T’au Empire",
    "season": 1,
    "boxNumber": 2,
    "boxName": "Chalnath",
    "category": "Horde",
    "operatives": 11,
    "wounds": 84,
    "apl": 23,
    "releaseDate": "2021-11-01",
    "minOperatives": 11,
    "maxOperatives": 12,
    "minWounds": 83,
    "maxWounds": 86,
    "minApl": 23,
    "maxApl": 24,
    "minActivations": 7,
    "maxActivations": 12,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Corsair Voidscarred",
    "genericFaction": "Xenos",
    "fortyKFaction": "Aeldari",
    "season": 1,
    "boxNumber": 3,
    "boxName": "Nachmund",
    "category": "Standard",
    "operatives": 9,
    "wounds": 73,
    "apl": 18,
    "releaseDate": "2022-03-01",
    "minOperatives": 9,
    "maxOperatives": 9,
    "minWounds": 73,
    "maxWounds": 73,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 9,
    "maxActivations": 9,
    "killOp": 9,
    "trooperApl": 2
  },
  {
    "killTeam": "Legionaries",
    "genericFaction": "Chaos",
    "fortyKFaction": "Chaos Space Marines",
    "season": 1,
    "boxNumber": 3,
    "boxName": "Nachmund",
    "category": "Elite",
    "operatives": 6,
    "wounds": 85,
    "apl": 18,
    "releaseDate": "2022-03-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 85,
    "maxWounds": 85,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Blooded",
    "genericFaction": "Chaos",
    "fortyKFaction": "Chaos Space Marines",
    "season": 1,
    "boxNumber": 4,
    "boxName": "Moroch",
    "category": "Horde",
    "operatives": 13,
    "wounds": 104,
    "apl": 28,
    "releaseDate": "2022-06-01",
    "minOperatives": 12,
    "maxOperatives": 14,
    "minWounds": 94,
    "maxWounds": 104,
    "minApl": 24,
    "maxApl": 28,
    "minActivations": 8,
    "maxActivations": 12,
    "killOp": 12,
    "trooperApl": 2
  },
  {
    "killTeam": "Phobos Strike Team",
    "genericFaction": "Imperium",
    "fortyKFaction": "Space Marines",
    "season": 1,
    "boxNumber": 4,
    "boxName": "Moroch",
    "category": "Elite",
    "operatives": 6,
    "wounds": 73,
    "apl": 18,
    "releaseDate": "2022-06-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 73,
    "maxWounds": 73,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Imperial Navy Breachers",
    "genericFaction": "Imperium",
    "fortyKFaction": "Imperial Agents",
    "season": 2,
    "boxNumber": 5,
    "boxName": "Into The Dark",
    "category": "Horde",
    "operatives": 12,
    "wounds": 96,
    "apl": 24,
    "releaseDate": "2022-08-01",
    "minOperatives": 11,
    "maxOperatives": 12,
    "minWounds": 89,
    "maxWounds": 96,
    "minApl": 22,
    "maxApl": 24,
    "minActivations": 11,
    "maxActivations": 12,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Farstalker Kinband",
    "genericFaction": "Xenos",
    "fortyKFaction": "T’au Empire",
    "season": 2,
    "boxNumber": 5,
    "boxName": "Into The Dark",
    "category": "Horde",
    "operatives": 12,
    "wounds": 96,
    "apl": 24,
    "releaseDate": "2022-08-01",
    "minOperatives": 12,
    "maxOperatives": 12,
    "minWounds": 95,
    "maxWounds": 98,
    "minApl": 24,
    "maxApl": 24,
    "minActivations": 12,
    "maxActivations": 12,
    "killOp": 12,
    "trooperApl": 2
  },
  {
    "killTeam": "Kasrkin",
    "genericFaction": "Imperium",
    "fortyKFaction": "Astra Militarum",
    "season": 2,
    "boxNumber": 6,
    "boxName": "Shadowvaults",
    "category": "Standard",
    "operatives": 10,
    "wounds": 81,
    "apl": 21,
    "releaseDate": "2022-10-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 81,
    "maxWounds": 81,
    "minApl": 21,
    "maxApl": 21,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Hierotek Circle",
    "genericFaction": "Xenos",
    "fortyKFaction": "Necrons",
    "season": 2,
    "boxNumber": 6,
    "boxName": "Shadowvaults",
    "category": "Semi-Elite",
    "operatives": 8,
    "wounds": 76,
    "apl": 18,
    "releaseDate": "2022-10-01",
    "minOperatives": 8,
    "maxOperatives": 8,
    "minWounds": 74,
    "maxWounds": 76,
    "minApl": 17,
    "maxApl": 18,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 5,
    "trooperApl": 2
  },
  {
    "killTeam": "Hand of the Archon",
    "genericFaction": "Xenos",
    "fortyKFaction": "Drukhari",
    "season": 2,
    "boxNumber": 7,
    "boxName": "Soulshackle",
    "category": "Standard",
    "operatives": 9,
    "wounds": 73,
    "apl": 18,
    "releaseDate": "2023-02-01",
    "minOperatives": 9,
    "maxOperatives": 9,
    "minWounds": 73,
    "maxWounds": 73,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 9,
    "maxActivations": 9,
    "killOp": 9,
    "trooperApl": 2
  },
  {
    "killTeam": "Exaction Squad",
    "genericFaction": "Imperium",
    "fortyKFaction": "Imperial Agents",
    "season": 2,
    "boxNumber": 7,
    "boxName": "Soulshackle",
    "category": "Horde",
    "operatives": 11,
    "wounds": 89,
    "apl": 22,
    "releaseDate": "2023-02-01",
    "minOperatives": 11,
    "maxOperatives": 11,
    "minWounds": 89,
    "maxWounds": 89,
    "minApl": 22,
    "maxApl": 22,
    "minActivations": 11,
    "maxActivations": 11,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Fellgor Ravagers",
    "genericFaction": "Chaos",
    "fortyKFaction": "Chaos Space Marines",
    "season": 2,
    "boxNumber": 9,
    "boxName": "Gallowfall",
    "category": "Standard",
    "operatives": 10,
    "wounds": 101,
    "apl": 20,
    "releaseDate": "2023-05-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 101,
    "maxWounds": 101,
    "minApl": 20,
    "maxApl": 20,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Hearthkyn Salvagers",
    "genericFaction": "Xenos",
    "fortyKFaction": "Leagues of Votann",
    "season": 2,
    "boxNumber": 9,
    "boxName": "Gallowfall",
    "category": "Standard",
    "operatives": 10,
    "wounds": 81,
    "apl": 20,
    "releaseDate": "2023-05-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 81,
    "maxWounds": 81,
    "minApl": 20,
    "maxApl": 20,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Chaos Cult",
    "genericFaction": "Chaos",
    "fortyKFaction": "Chaos Space Marines",
    "season": 3,
    "boxNumber": 8,
    "boxName": "Ashes of Faith",
    "category": "Horde",
    "operatives": 14,
    "wounds": 103,
    "apl": 28,
    "releaseDate": "2023-05-01",
    "minOperatives": 14,
    "maxOperatives": 14,
    "minWounds": 103,
    "maxWounds": 103,
    "minApl": 28,
    "maxApl": 28,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 14,
    "trooperApl": 2
  },
  {
    "killTeam": "Inquisitorial Agents",
    "genericFaction": "Imperium",
    "fortyKFaction": "Imperial Agents",
    "season": 3,
    "boxNumber": 8,
    "boxName": "Ashes of Faith",
    "category": "Horde",
    "operatives": 12,
    "wounds": 98,
    "apl": 24,
    "releaseDate": "2023-05-01",
    "minOperatives": 12,
    "maxOperatives": 13,
    "minWounds": 88,
    "maxWounds": 98,
    "minApl": 22,
    "maxApl": 24,
    "minActivations": 11,
    "maxActivations": 12,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Blades of Khaine",
    "genericFaction": "Xenos",
    "fortyKFaction": "Aeldari",
    "season": 3,
    "boxNumber": 10,
    "boxName": "Salvation",
    "category": "Semi-Elite",
    "operatives": 8,
    "wounds": 65,
    "apl": 24,
    "releaseDate": "2024-01-01",
    "minOperatives": 8,
    "maxOperatives": 8,
    "minWounds": 65,
    "maxWounds": 65,
    "minApl": 24,
    "maxApl": 24,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 8,
    "trooperApl": 3
  },
  {
    "killTeam": "Scout Squad",
    "genericFaction": "Imperium",
    "fortyKFaction": "Space Marines",
    "season": 3,
    "boxNumber": 10,
    "boxName": "Salvation",
    "category": "Standard",
    "operatives": 9,
    "wounds": 91,
    "apl": 19,
    "releaseDate": "2024-01-01",
    "minOperatives": 9,
    "maxOperatives": 9,
    "minWounds": 91,
    "maxWounds": 91,
    "minApl": 19,
    "maxApl": 19,
    "minActivations": 9,
    "maxActivations": 9,
    "killOp": 9,
    "trooperApl": 2
  },
  {
    "killTeam": "Nemesis Claw",
    "genericFaction": "Chaos",
    "fortyKFaction": "Chaos Space Marines",
    "season": 3,
    "boxNumber": 11,
    "boxName": "Nightmare",
    "category": "Elite",
    "operatives": 6,
    "wounds": 85,
    "apl": 18,
    "releaseDate": "2024-04-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 85,
    "maxWounds": 85,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Mandrakes",
    "genericFaction": "Xenos",
    "fortyKFaction": "Drukhari",
    "season": 3,
    "boxNumber": 11,
    "boxName": "Nightmare",
    "category": "Standard",
    "operatives": 9,
    "wounds": 73,
    "apl": 18,
    "releaseDate": "2024-04-01",
    "minOperatives": 9,
    "maxOperatives": 9,
    "minWounds": 73,
    "maxWounds": 73,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 9,
    "maxActivations": 9,
    "killOp": 9,
    "trooperApl": 2
  },
  {
    "killTeam": "Brood Brothers",
    "genericFaction": "Xenos",
    "fortyKFaction": "Genestealer Cults",
    "season": 3,
    "boxNumber": 12,
    "boxName": "Termination",
    "category": "Horde",
    "operatives": 13,
    "wounds": 86,
    "apl": 27,
    "releaseDate": "2024-06-01",
    "minOperatives": 10,
    "maxOperatives": 14,
    "minWounds": 71,
    "maxWounds": 91,
    "minApl": 20,
    "maxApl": 27,
    "minActivations": 6,
    "maxActivations": 12,
    "killOp": 13,
    "trooperApl": 2
  },
  {
    "killTeam": "Hernkyn Yaegirs",
    "genericFaction": "Xenos",
    "fortyKFaction": "Leagues of Votann",
    "season": 3,
    "boxNumber": 12,
    "boxName": "Termination",
    "category": "Standard",
    "operatives": 10,
    "wounds": 81,
    "apl": 20,
    "releaseDate": "2024-06-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 81,
    "maxWounds": 81,
    "minApl": 20,
    "maxApl": 20,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Tempestus Aquilons",
    "genericFaction": "Imperium",
    "fortyKFaction": "Astra Militarum",
    "season": 4,
    "boxNumber": 13,
    "boxName": "Hivestorm",
    "category": "Horde",
    "operatives": 11,
    "wounds": 91,
    "apl": 23,
    "releaseDate": "2024-09-01",
    "minOperatives": 11,
    "maxOperatives": 11,
    "minWounds": 91,
    "maxWounds": 91,
    "minApl": 23,
    "maxApl": 23,
    "minActivations": 11,
    "maxActivations": 11,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Vespid Stingwings",
    "genericFaction": "Xenos",
    "fortyKFaction": "T’au Empire",
    "season": 4,
    "boxNumber": 13,
    "boxName": "Hivestorm",
    "category": "Horde",
    "operatives": 11,
    "wounds": 96,
    "apl": 22,
    "releaseDate": "2024-09-01",
    "minOperatives": 11,
    "maxOperatives": 11,
    "minWounds": 96,
    "maxWounds": 96,
    "minApl": 22,
    "maxApl": 22,
    "minActivations": 11,
    "maxActivations": 11,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Plague Marines",
    "genericFaction": "Chaos",
    "fortyKFaction": "Death Guard",
    "season": 4,
    "boxNumber": 14,
    "boxName": "Starter Set",
    "category": "Elite",
    "operatives": 6,
    "wounds": 85,
    "apl": 18,
    "releaseDate": "2024-11-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 85,
    "maxWounds": 85,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Angels of Death",
    "genericFaction": "Imperium",
    "fortyKFaction": "Space Marines",
    "season": 4,
    "boxNumber": 14,
    "boxName": "Starter Set",
    "category": "Elite",
    "operatives": 6,
    "wounds": 89,
    "apl": 18,
    "releaseDate": "2024-11-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 83,
    "maxWounds": 89,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Ratlings",
    "genericFaction": "Imperium",
    "fortyKFaction": "Astra Militarum",
    "season": 4,
    "boxNumber": 15,
    "boxName": "Brutal and Cunning",
    "category": "Horde",
    "operatives": 11,
    "wounds": 97,
    "apl": 22,
    "releaseDate": "2024-12-01",
    "minOperatives": 11,
    "maxOperatives": 11,
    "minWounds": 65,
    "maxWounds": 97,
    "minApl": 22,
    "maxApl": 22,
    "minActivations": 11,
    "maxActivations": 11,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Wrecka Crew",
    "genericFaction": "Xenos",
    "fortyKFaction": "Orks",
    "season": 4,
    "boxNumber": 15,
    "boxName": "Brutal and Cunning",
    "category": "Semi-Elite",
    "operatives": 8,
    "wounds": 84,
    "apl": 16,
    "releaseDate": "2024-12-01",
    "minOperatives": 8,
    "maxOperatives": 8,
    "minWounds": 84,
    "maxWounds": 90,
    "minApl": 16,
    "maxApl": 16,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 6,
    "trooperApl": 2
  },
  {
    "killTeam": "Sanctifiers",
    "genericFaction": "Imperium",
    "fortyKFaction": "Adepta Sororitas",
    "season": 4,
    "boxNumber": 16,
    "boxName": "Blood and Zeal",
    "category": "Horde",
    "operatives": 11,
    "wounds": 81,
    "apl": 23,
    "releaseDate": "2025-03-01",
    "minOperatives": 11,
    "maxOperatives": 11,
    "minWounds": 78,
    "maxWounds": 81,
    "minApl": 22,
    "maxApl": 23,
    "minActivations": 11,
    "maxActivations": 11,
    "killOp": 11,
    "trooperApl": 2
  },
  {
    "killTeam": "Goremongers",
    "genericFaction": "Chaos",
    "fortyKFaction": "World Eaters",
    "season": 4,
    "boxNumber": 16,
    "boxName": "Blood and Zeal",
    "category": "Semi-Elite",
    "operatives": 8,
    "wounds": 81,
    "apl": 16,
    "releaseDate": "2025-03-01",
    "minOperatives": 8,
    "maxOperatives": 8,
    "minWounds": 81,
    "maxWounds": 81,
    "minApl": 16,
    "maxApl": 16,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 8,
    "trooperApl": 2
  },
  {
    "killTeam": "Battleclade",
    "genericFaction": "Imperium",
    "fortyKFaction": "Adeptus Mechanicus",
    "season": 4,
    "boxNumber": 17,
    "boxName": "Typhon",
    "category": "Standard",
    "operatives": 10,
    "wounds": 88,
    "apl": 22,
    "releaseDate": "2025-06-01",
    "minOperatives": 10,
    "maxOperatives": 10,
    "minWounds": 82,
    "maxWounds": 88,
    "minApl": 22,
    "maxApl": 22,
    "minActivations": 10,
    "maxActivations": 10,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Raveners",
    "genericFaction": "Xenos",
    "fortyKFaction": "Tyranids",
    "season": 4,
    "boxNumber": 17,
    "boxName": "Typhon",
    "category": "Elite",
    "operatives": 5,
    "wounds": 101,
    "apl": 15,
    "releaseDate": "2025-06-01",
    "minOperatives": 5,
    "maxOperatives": 5,
    "minWounds": 101,
    "maxWounds": 101,
    "minApl": 15,
    "maxApl": 15,
    "minActivations": 5,
    "maxActivations": 5,
    "killOp": 5,
    "trooperApl": 3
  },
  {
    "killTeam": "Canoptek Circle",
    "genericFaction": "Xenos",
    "fortyKFaction": "Necrons",
    "season": 5,
    "boxNumber": 18,
    "boxName": "Tomb World",
    "category": "Semi-Elite",
    "operatives": 8,
    "wounds": 91,
    "apl": 17,
    "releaseDate": "2025-08-01",
    "minOperatives": 8,
    "maxOperatives": 8,
    "minWounds": 91,
    "maxWounds": 91,
    "minApl": 17,
    "maxApl": 17,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 5,
    "trooperApl": 2
  },
  {
    "killTeam": "Deathwatch",
    "genericFaction": "Imperium",
    "fortyKFaction": "Space Marines",
    "season": 5,
    "boxNumber": 18,
    "boxName": "Tomb World",
    "category": "Elite",
    "operatives": 5,
    "wounds": 78,
    "apl": 15,
    "releaseDate": "2025-08-01",
    "minOperatives": 5,
    "maxOperatives": 5,
    "minWounds": 61,
    "maxWounds": 78,
    "minApl": 15,
    "maxApl": 15,
    "minActivations": 5,
    "maxActivations": 5,
    "killOp": 5,
    "trooperApl": 3
  },
  {
    "killTeam": "Wolf Scouts",
    "genericFaction": "Imperium",
    "fortyKFaction": "Space Marines",
    "season": 5,
    "boxNumber": 19,
    "boxName": "Dead Silence",
    "category": "Elite",
    "operatives": 6,
    "wounds": 75,
    "apl": 17,
    "releaseDate": "2025-11-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 74,
    "maxWounds": 75,
    "minApl": 17,
    "maxApl": 17,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "XV26 Stealth Battlesuits",
    "genericFaction": "Xenos",
    "fortyKFaction": "T’au Empire",
    "season": 5,
    "boxNumber": 19,
    "boxName": "Dead Silence",
    "category": "Semi-Elite",
    "operatives": 7,
    "wounds": 75,
    "apl": 19,
    "releaseDate": "2025-11-01",
    "minOperatives": 7,
    "maxOperatives": 7,
    "minWounds": 75,
    "maxWounds": 75,
    "minApl": 19,
    "maxApl": 19,
    "minActivations": 7,
    "maxActivations": 7,
    "killOp": 5,
    "trooperApl": 3
  },
  {
    "killTeam": "Celestial Insidiants",
    "genericFaction": "Imperium",
    "fortyKFaction": "Adepta Sororitas",
    "season": 5,
    "boxNumber": 20,
    "boxName": "Shadowhunt",
    "category": "Standard",
    "operatives": 9,
    "wounds": 93,
    "apl": 19,
    "releaseDate": "2026-02-01",
    "minOperatives": 9,
    "maxOperatives": 9,
    "minWounds": 91,
    "maxWounds": 93,
    "minApl": 19,
    "maxApl": 19,
    "minActivations": 9,
    "maxActivations": 9,
    "killOp": 9,
    "trooperApl": 2
  },
  {
    "killTeam": "Murderwing",
    "genericFaction": "Chaos",
    "fortyKFaction": "Chaos Space Marines",
    "season": 5,
    "boxNumber": 20,
    "boxName": "Shadowhunt",
    "category": "Elite",
    "operatives": 6,
    "wounds": 85,
    "apl": 18,
    "releaseDate": "2026-02-01",
    "minOperatives": 6,
    "maxOperatives": 6,
    "minWounds": 85,
    "maxWounds": 85,
    "minApl": 18,
    "maxApl": 18,
    "minActivations": 6,
    "maxActivations": 6,
    "killOp": 6,
    "trooperApl": 3
  },
  {
    "killTeam": "Spectres",
    "genericFaction": "Imperium",
    "fortyKFaction": "Astra Militarum",
    "season": 5,
    "boxNumber": 21,
    "boxName": "Terror on Devlan",
    "category": "Horde",
    "operatives": 11,
    "wounds": 84,
    "apl": 21,
    "releaseDate": "2026-05-01",
    "minOperatives": 11,
    "maxOperatives": 11,
    "minWounds": 84,
    "maxWounds": 84,
    "minApl": 21,
    "maxApl": 21,
    "minActivations": 11,
    "maxActivations": 11,
    "killOp": 10,
    "trooperApl": 2
  },
  {
    "killTeam": "Exodites",
    "genericFaction": "Xenos",
    "fortyKFaction": "Aeldari",
    "season": 5,
    "boxNumber": 22,
    "boxName": "Exodite",
    "category": "Elite",
    "operatives": 5,
    "wounds": 86,
    "apl": 16,
    "releaseDate": "2026-07-01",
    "minOperatives": 5,
    "maxOperatives": 5,
    "minWounds": 86,
    "maxWounds": 86,
    "minApl": 16,
    "maxApl": 16,
    "minActivations": 8,
    "maxActivations": 8,
    "killOp": 5,
    "trooperApl": 4
  }
]] 

export const MAPS = await loadMaps()
export const MATCHES = await loadMatches()