export const TEAM_EMOJIS: Record<string, string> = {
  'Strike Force Variel': '🫥',
  'Hunter Clade': '🤖',
  'Void-dancer Troupe': '🤡',
  'Gellerpox Infected': '🫃',
  Wyrmblade: '🪱',
  'Elucidian Starstriders': '🛰️',
  Warpcoven: '🧙‍♂️',
  'Death Korps': '🧑‍🤝‍🧑',
  Kommandos: '🍄',
  Novitiates: '✝️',
  Pathfinders: '🚴‍♂️',
  'Corsair Voidscarred': '🏴‍☠️',
  Legionaries: '✴️',
  Blooded: '💉',
  'Phobos Strike Team': '🪶',
  'Imperial Navy Breachers': '🛡️',
  'Farstalker Kinband': '🦎',
  Kasrkin: '💔',
  'Hierotek Circle': '🧟‍♂️',
  'Hand of the Archon': '🍆',
  'Exaction Squad': '👮‍♂️',
  'Fellgor Ravagers': '🐐',
  'Hearthkyn Salvagers': '🚸',
  'Chaos Cult': '🔯',
  'Inquisitorial Agents': '🕴️',
  'Blades of Khaine': '💎',
  'Scout Squad': '🔪',
  'Nemesis Claw': '🦇',
  Mandrakes: '🫣',
  'Brood Brothers': '👨‍🦲',
  'Hernkyn Yaegirs': '🤠',
  'Tempestus Aquilons': '🚦',
  'Vespid Stingwings': '🐝',
  'Plague Marines': '💩',
  'Angels of Death': '👼',
  Ratlings: '🥪',
  'Wrecka Crew': '💣',
  Sanctifiers: '🗣️',
  Goremongers: '🩸',
  Battleclade: '🦾',
  Raveners: '🐛',
  'Canoptek Circle': '🕷️',
  Deathwatch: '⌚',
  'Wolf Scouts': '🐺',
  'XV26 Stealth Battlesuits': '🙈',
  'Celestial Insidiants': '⚜️',
  Murderwing: '🧚‍♂️',
  Spectres: '🪖',
  Exodites: '🦖',
  Greenskins: '🧌',
  Ecclesiarchy: '⛪',
  Ogryns: '🦍',
}
